version: "3"
services:
  nyancat:
    build: .
    image: nyan-cat:latest
    ports:
      - "7777:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/app/venv/bin:$PATH
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /volume1/Web/nginx.conf:/etc/nginx/nginx.conf
      - /usr/builtin/etc/certificate:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx  # Partager les logs avec fail2ban
    depends_on:
      - nyancat

  fail2ban:
    image: crazymax/fail2ban:latest
    volumes:
      - nginx-logs:/var/log/nginx  # Même volume de logs
      - /volume1/Web/fail2ban.conf:/etc/fail2ban/fail2ban.conf
      - /volume1/Web/jail.conf:/etc/fail2ban/jail.conf
    cap_add:
      - NET_ADMIN  # Permettre à fail2ban de gérer les règles réseau
    depends_on:
      - nginx

volumes:
  nginx-logs:
