version: "3"
services:
  nyan-cat:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/app/venv/bin:$PATH
    command: /app/venv/bin/flask run --host=0.0.0.0