version: "3"
services:
  nyancat:
    build: .
    image: nyan-cat:latest
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/app/venv/bin:$PATH
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
    command: /app/venv/bin/flask run --host=0.0.0.0 --port=5000 --with-threads --cert=ssl/ssl.crt --key=ssl/ssl.key
    tty: true