version: "3"
services:
  nyancat:
    build: .
    image: nyan-cat:latest
    shm_size: '512m'
    ports:
      - "7777:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/root/.local/share/pipx/venvs/gunicorn/bin:$PATH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
      - ./proxies.txt:/app/proxies.txt
    tty: true
    depends_on:
      - redis

  celery-worker-pretranslate:
    build: .
    image: nyan-cat:latest
    container_name: "celery-worker-pretranslate"
    depends_on:
      - nyancat
      - redis
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/root/.local/share/pipx/venvs/gunicorn/bin:$PATH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_QUEUE=pretranslate
    command: >
      celery -A app.celery worker
      --loglevel=info
      --concurrency=2
      --prefetch-multiplier=1
      -Q pretranslate
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
      - ./proxies.txt:/app/proxies.txt

  celery-worker-proxy:
    build: .
    image: nyan-cat:latest
    container_name: "celery-worker-proxy"
    depends_on:
      - nyancat
      - redis
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/root/.local/share/pipx/venvs/gunicorn/bin:$PATH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_QUEUE=proxyupdate
    command: >
      celery -A app.celery worker
      --loglevel=info
      --concurrency=1
      --prefetch-multiplier=1
      -Q proxyupdate
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
      - ./proxies.txt:/app/proxies.txt

  celery-beat:
    build: .
    image: nyan-cat:latest
    container_name: "celery-beat"
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/root/.local/share/pipx/venvs/gunicorn/bin:$PATH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      celery -A app.celery beat
      --loglevel=info
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
      - ./proxies.txt:/app/proxies.txt

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /volume1/Web/nginx.conf:/etc/nginx/nginx.conf
      - /usr/builtin/etc/certificate:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx
    depends_on:
      - nyancat

  redis:
    image: redis:7-alpine
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  nginx-logs:
  redis-data:
