version: "3"
services:
  nyancat:
    build: .
    image: nyan-cat:latest
    shm_size: '512m'
    ports:
      - "7777:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/root/.local/share/pipx/venvs/gunicorn/bin:$PATH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LANGUAGETOOL_HOST=languagetool
      - LANGUAGETOOL_PORT=8010
    volumes:
      - lt-added:/app/lt-added
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
      - /share/Docker/NyanCAT/proxies.txt:/app/proxies.txt
    tty: true
    depends_on:
      - redis
      - languagetool

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /volume1/Web/nginx.conf:/etc/nginx/nginx.conf
      - /usr/builtin/etc/certificate:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx
    depends_on:
      - nyancat

  redis:
    image: redis:7-alpine
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool
    environment:
      - Java_Xms=512m
      - Java_Xmx=1g
    ports:
      - "8010:8010"
    volumes:
      - lt-added:/lt-added
    user: root
    command: >
      bash -c "cp -r /LanguageTool/org/languagetool/resource/* /lt-added &&  chmod 777 /LanguageTool/start.sh &&
               /LanguageTool/start.sh"
volumes:
  nginx-logs:
  redis-data:
  lt-added:
