version: "3"
services:
  nyancat:
    build: .
    image: nyan-cat:latest
    shm_size: '256m'
    ports:
      - "7777:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PATH=/root/.local/share/pipx/venvs/gunicorn/bin:$PATH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /usr/builtin/etc/certificate:/app/ssl
      - /share/Docker/NyanCAT/fileproject:/app/fileproject
      - /share/Docker/NyanCAT/database:/app/database
    tty: true
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /volume1/Web/nginx.conf:/etc/nginx/nginx.conf
      - /usr/builtin/etc/certificate:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx
    depends_on:
      - nyancat

  fail2ban:
    image: crazymax/fail2ban:latest
    volumes:
      - nginx-logs:/var/log/nginx
      - /volume1/Web/fail2ban:/etc/fail2ban/
    cap_add:
      - NET_ADMIN
    depends_on:
      - nginx

  redis:
    image: redis:7-alpine
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  nginx-logs:
  redis-data:

networks:
  default:
    driver: bridge
